# This workflow Builds the UFS SRWEATHER APP
name: Build SRWA

on:
# Enable the ability to manually run this workflow, as well as when the ci-aws-intel-build label is attached
  workflow_dispatch:
  pull_request:
    branches: 
      - rrfs_ci 
    types: 
      - labeled 

# Use a default login shell which loads intel/oneapi/setvars.sh, and lmod path 
defaults:
  run:
    shell: bash -l {0}

jobs:
  
  Configure_SRWA:
    name: Checkout SRWA in parent directory 
    runs-on: self-hosted 
    if: ${{ github.event.label.name == 'ci-aws-intel-build' }}

    steps:
      # Checkout the SRWA - in parent directory, with commit sha-1 in filepath to avoid multiple PR Conflicts, & track build tests by commit
      # Specify branch used for testing, if there is not a similar named branch in ufs-SRWA
      - name: Checkout SRWA 
        run: |
          cd ../
          mkdir ${{ github.sha }} && cd ${{ github.sha }} 
          git clone https://github.com/NOAA-GSL/ufs-srweather-app.git
          cd ufs-srweather-app
          
          echo "Github.ref_name" ${{ github.ref_name }} 
          echo "Github.base_ref" ${{ github.base_ref }} 
          echo "Github.head_ref" ${{ github.head_ref }}

          exists=`git show-ref ${{ github.ref }}`
          if [ -n "$exists" ]; then
            echo 'branch exists!'
            git checkout ${{ github.ref_name }}
          else
            git checkout ${{ github.base_ref }}
          fi
          git branch -a
      
      - name: Checkout Externals & Delete Regional Workflow
        run: |
          cd ../${{ github.sha }}/ufs-srweather-app
          ./manage_externals/checkout_externals
          rm -rf regional_workflow
         
      - name: Checkout this version of Regional Workflow
        uses: actions/checkout@v3
        with:
          clean: false
       
      - name: Insert this Version of Regional Workflow
        run: |
          cp -r ${{ github.workspace }} ../${{ github.sha }}/ufs-srweather-app/regional_workflow
  
  Build_SRWA:
    name: Build SRWA 
    if: ${{ github.event.label.name == 'ci-aws-intel-build' }}
    runs-on: self-hosted
    needs: Configure_SRWA 
    
    steps:
      - name: Build Short Range Weather App using test/build.sh
        run: |
          cd ../${{ github.sha }}/ufs-srweather-app/test/
          ./build.sh aws 2>&1 | tee build_test.out
